name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install/setup
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential

      - name: install/gcc-5
        run: |
          sudo apt-get -y install gcc-5 g++-5

      - name: install/boost
        run: |
          cd ${BUILD_PATH}
          git clone --recursive https://github.com/boostorg/boost.git
          cd boost
          ./bootstrap.sh
          ./b2 toolset=gcc-5 --prefix=/usr/local -j5
          sudo ./b2 install toolset=gcc-5 --prefix=/usr/local -j5
        env:
          BUILD_PATH: /opt

      - name: install/cmake
        run: |
          cd ${BUILD_PATH}
          git clone https://gitlab.kitware.com/cmake/cmake.git
          cd cmake
          ./bootstrap --prefix=/usr/local
          make -j5
          sudo make install
        env:
          BUILD_PATH: /opt
          CC: gcc-5
          CXX: g++-5

      - name: build and test
        run: |
          export CMAKE_ROOT
          cd ${BUILD_PATH}
          mkdir build/
          cd build/
          cmake ..
          make
          ctest -V

        env:
          BUILD_PATH: /home/runner/work/lib/lib
          LIB_PATH: /home/runner/work/lib/lib/src
          BUILD_CND: /usr/bin/g++-5
          BOOST_PATH: /usr/local/include
          CC: gcc-5
          CXX: g++-5
          CMAKE_ROOT: /usr/local/share/cmake-3.15
