name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install/setup
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential

      - name: install/gcc-5
        run: |
          sudo apt-get -y install gcc-5

      - name: build
        run: |
          cd ${BUILD_PATH}
          wget https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/${BOOST_FILE}.tar.gz --no-check-certificate
          tar xfz ${BOOST_FILE}.tar.gz
          rm ${BOOST_FILE}.tar.gz
          ls
        env:
          BUILD_PATH: /opt
          BOOST_VERSION: 1.71.0
          BOOST_FILE: boost_1_71_0
