name: C/C++ CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cmake test
        uses: docker://btk15049/ci-env:20190929
        env:
          LIB_PATH: /app/lib/src
          BUILD_CND: /usr/bin/g++-5
          BOOST_PATH: /usr/local/include
