name: C/C++ CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test
        uses: docker://btk15049/ci-env:20190929
        with:
          args: 
            mkdir build/ \
            && cd build/ \
            && cmake .. \
            && make \
            && ctest -V
        env:
          BUILD_PATH: /home/runner/work/lib/lib
          LIB_PATH: /home/runner/work/lib/lib/src
          BUILD_CND: /usr/bin/g++-5
          BOOST_PATH: /usr/local/include
          CC: gcc-5
          CXX: g++-5
          CMAKE_ROOT: /usr/local/share/cmake-3.15
