name: C/C++ CI

on:
  push:
    branches:
      - "*"
      - "!docker*"

jobs:
  CTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cmake test
        uses: docker://docker.pkg.github.com/btk15049/ctest-with-boost:20191005
        env:
          LIB_PATH: /github/workspace/src
          BUILD_CMD: /usr/bin/g++-5
          BOOST_PATH: /usr/local/include
