name: C/C++ CI

on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/ctest.yml"
  push:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/ctest.yml"

jobs:
  test:
    name: CTest
    steps:
      - uses: docker://ghcr.io/btk15049/ctest
        name: Run test
