name: C/C++ CI

on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/ctest.yml"
  push:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/ctest.yml"

jobs:
  test:
    name: CTest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PULL_FROM_PACKAGE_REGISTRY }}
        run: docker login docker.pkg.github.com -u btk15049 -p $GITHUB_TOKEN
      - name: Pull image from GitHub Package Registry
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ctest
        run: |
          docker pull ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
          docker tag ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest ctest
      - name: Run test
        run: docker run -v /home/runner/work/lib/lib:/app ctest
