name: Docker build CI

on:
  push:
    branches:
      - "docker*"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}
        run: docker login docker.pkg.github.com -u btk15049 -p $GITHUB_TOKEN
      - name: Build docker image
        run: |
          docker build -t current .
      - name: Push docker image
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ctest-with-boost
        run: |
          TAG=`date "+%Y%m%d"`
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
  test:
    name: CTest using published image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: btk15049
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN_TO_PULL_FROM_PACKAGE_REGISTRY }}
      - name: Pull from GitHub Package Registry
        uses: actions/docker/cli@master
        with:
          args: '"pull ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest" "tag ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest current"'
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ctest-with-boost
