name: Docker build CI

on:
  push:
    branches:
      - "docker*"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}
        run: docker login docker.pkg.github.com -u btk15049 -p $GITHUB_TOKEN
      - name: Build docker image
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ctest-with-boost
        run: |
          TAG=`date "+%Y%m%d"`
          docker build -t ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG} .
      - name: Push docker image
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ctest-with-boost
        run: |
          TAG=`date "+%Y%m%d"`
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
  test:
    needs: build
    name: CTest using published image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cmake test
        uses: docker://docker.pkg.github.com/btk15049/ctest-with-boost:latest
        env:
          LIB_PATH: /github/workspace/src
          BUILD_CMD: /usr/bin/g++-5
          BOOST_PATH: /usr/local/include
