name: Docker build CI

on:
  push:
    paths:
      - "docker/*"
      - .github/workflows/docker-build.yml

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u btk15049 --password-stdin
      - name: Build docker image
        run: |
          docker build -t current docker
      - name: Push docker image
        env:
          CONTAINER_REGISTRY_PATH: ghcr.io/btk15049
          IMAGE_NAME: ctest
        run: |
          TAG=`date "+%Y%m%d"`
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
